### ISSUE TITLE
Mismatch between set and displayed date

### ISSUE THREAD

**Issue by mudrd8mz** [soorajsingh/moodle-availability_enroldate#2]
When I configure a module and I set its availability condition "Enrolment date must be before" and I leave the time as default 00:00

![image](https://user-images.githubusercontent.com/85831/109941136-21af1c80-7cd3-11eb-86ff-86061c985d5c.png)

then the course main page seems to display one day earlier:

![image](https://user-images.githubusercontent.com/85831/109941071-0a702f00-7cd3-11eb-87a4-2e2f14a933c6.png)

This can be confusing.

**Comment by mudrd8mz** [comment]
It is likely related to what `show_time()` method does.

**Comment by soorajsingh** [comment]
its fixed now
