### ISSUE TITLE
Is this plugin dead ?

### ISSUE THREAD

**Issue by rabser** [soorajsingh/moodle-availability_enroldate#4]
No changes from too much time and no info about moodle 4.x which is the current release.
It's this plugin dead or not ?

**Comment by soorajsingh** [comment]
No change required for 4.x

**Comment by rabser** [comment]
Thanks for the prompt and kind response. I've seen that you updated also the compatibility of your plugin on the Moodle site: great!
Have a nice end of the year and a better new one!
